In [1]:
# new notebook!
# need to re-import libraries load data from files
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# read the data
census = pd.read_csv('./2018_nyc_squirrels_census.csv')
stories = pd.read_csv('./2018_nyc_squirrels_stories.csv')

"""
Exercise

Using the same process as above, read the file, 2018_nyc_squirrels_hectares.csv, into a dataframe named 'hectares.'

"""
# solution
hetares = pd.read_csv('./2018_nyc_squirrels_hectares.csv')

In [4]:
# inspecting data
# we do this for many reasons - minimally, I use it as a sanity check (any data corrupted during download?
# any character encoding problems? etc.
census

,x,y,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,combination_of_primary_and,running,chasing,...,geocoded_column,primary_fur_color,location,above_ground_sighter,age,color_notes,highlight_fur_color,specific_location,other_activities,other_interactions
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,+,False,False,...,"{'type': 'Point', 'coordinates': [-73.95613449...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,+,False,False,...,"{'type': 'Point', 'coordinates': [-73.96885746...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,Gray+,False,True,...,"{'type': 'Point', 'coordinates': [-73.97428114...",Gray,Above Ground,10,NaN,NaN,NaN,NaN,NaN,NaN
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Gray+,False,False,...,"{'type': 'Point', 'coordinates': [-73.95964139...",Gray,NaN,NaN,Adult,Nothing selected as Primary. Gray selected as ...,NaN,NaN,NaN,NaN
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Gray+Cinnamon,False,False,...,"{'type': 'Point', 'coordinates': [-73.97026764...",Gray,Above Ground,NaN,Adult,NaN,Cinnamon,on tree stump,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Gray+,False,False,...,"{'type': 'Point', 'coordinates': [-73.96394313...",Gray,Ground Plane,FALSE,Adult,NaN,NaN,NaN,NaN,NaN
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Gray+White,False,False,...,"{'type': 'Point', 'coordinates': [-73.97040158...",Gray,Ground Plane,FALSE,Adult,NaN,White,NaN,NaN,NaN
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,"Gray+Black, Cinnamon, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.96658719...",Gray,Ground Plane,FALSE,Adult,NaN,"Black, Cinnamon, White",NaN,NaN,NaN
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,"Gray+Cinnamon, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.96399412...",Gray,Ground Plane,FALSE,NaN,NaN,"Cinnamon, White",NaN,NaN,NaN
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,"Cinnamon+Gray, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.97547941...",Cinnamon,Ground Plane,FALSE,Adult,NaN,"Gray, White",NaN,NaN,NaN

In [5]:
# first five rows
census.head()

,x,y,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,combination_of_primary_and,running,chasing,...,geocoded_column,primary_fur_color,location,above_ground_sighter,age,color_notes,highlight_fur_color,specific_location,other_activities,other_interactions
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,+,False,False,...,"{'type': 'Point', 'coordinates': [-73.95613449...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,+,False,False,...,"{'type': 'Point', 'coordinates': [-73.96885746...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,Gray+,False,True,...,"{'type': 'Point', 'coordinates': [-73.97428114...",Gray,Above Ground,10,NaN,NaN,NaN,NaN,NaN,NaN
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Gray+,False,False,...,"{'type': 'Point', 'coordinates': [-73.95964139...",Gray,NaN,NaN,Adult,Nothing selected as Primary. Gray selected as ...,NaN,NaN,NaN,NaN
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Gray+Cinnamon,False,False,...,"{'type': 'Point', 'coordinates': [-73.97026764...",Gray,Above Ground,NaN,Adult,NaN,Cinnamon,on tree stump,NaN,NaN

In [8]:
# last five rows
# demonstrate with row count argument
census.tail()

,x,y,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,combination_of_primary_and,running,chasing,...,geocoded_column,primary_fur_color,location,above_ground_sighter,age,color_notes,highlight_fur_color,specific_location,other_activities,other_interactions
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Gray+,False,False,...,"{'type': 'Point', 'coordinates': [-73.96394313...",Gray,Ground Plane,FALSE,Adult,NaN,NaN,NaN,NaN,NaN
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Gray+White,False,False,...,"{'type': 'Point', 'coordinates': [-73.97040158...",Gray,Ground Plane,FALSE,Adult,NaN,White,NaN,NaN,NaN
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,"Gray+Black, Cinnamon, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.96658719...",Gray,Ground Plane,FALSE,Adult,NaN,"Black, Cinnamon, White",NaN,NaN,NaN
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,"Gray+Cinnamon, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.96399412...",Gray,Ground Plane,FALSE,NaN,NaN,"Cinnamon, White",NaN,NaN,NaN
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,"Cinnamon+Gray, White",False,False,...,"{'type': 'Point', 'coordinates': [-73.97547941...",Cinnamon,Ground Plane,FALSE,Adult,NaN,"Gray, White",NaN,NaN,NaN

In [9]:
# shape - an attribute, count of rows and cols
print(census.shape)

(3023, 31)

In [10]:
# index - also an attribute, in this case the number of rows but indexing in pandas is a big topic
print(census.index)

RangeIndex(start=0, stop=3023, step=1)

In [11]:
# data types
print(census.dtypes)

x                             float64
y                             float64
unique_squirrel_id             object
hectare                        object
shift                          object
date                            int64
hectare_squirrel_number         int64
combination_of_primary_and     object
running                          bool
chasing                          bool
climbing                         bool
eating                           bool
foraging                         bool
kuks                             bool
quaas                            bool
moans                            bool
tail_flags                       bool
tail_twitches                    bool
approaches                       bool
indifferent                      bool
runs_from                        bool
geocoded_column                object
primary_fur_color              object
location                       object
above_ground_sighter           object
age                            object
color_notes                    object
highlight_fur_color            object
specific_location              object
other_activities               object
other_interactions             object
dtype: object

In [13]:
# if you are only going to use one function to inspect your data
# info() includes all the info above in a single output
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   x                           3023 non-null   float64
 1   y                           3023 non-null   float64
 2   unique_squirrel_id          3023 non-null   object
 3   hectare                     3023 non-null   object
 4   shift                       3023 non-null   object
 5   date                        3023 non-null   int64
 6   hectare_squirrel_number     3023 non-null   int64
 7   combination_of_primary_and  3023 non-null   object
 8   running                     3023 non-null   bool
 9   chasing                     3023 non-null   bool
 10  climbing                    3023 non-null   bool
 11  eating                      3023 non-null   bool
 12  foraging                    3023 non-null   bool
 13  kuks                        3023 non-null   bool
 14  quaas                       3023 non-null   bool
 15  moans                       3023 non-null   bool
 16  tail_flags                  3023 non-null   bool
 17  tail_twitches               3023 non-null   bool
 18  approaches                  3023 non-null   bool
 19  indifferent                 3023 non-null   bool
 20  runs_from                   3023 non-null   bool
 21  geocoded_column             3023 non-null   object
 22  primary_fur_color           2968 non-null   object
 23  location                    2959 non-null   object
 24  above_ground_sighter        2909 non-null   object
 25  age                         2902 non-null   object
 26  color_notes                 182 non-null    object
 27  highlight_fur_color         1937 non-null   object
 28  specific_location           476 non-null    object
 29  other_activities            437 non-null    object
 30  other_interactions          240 non-null    object
dtypes: bool(13), float64(2), int64(2), object(14)
memory usage: 463.6+ KB

In [14]:
"""
Execise

Use the head() and info() functions to view information about the _census_ dataframe.

Note that the variable 'above_ground_sighter' is given a dtype of 'object' (str). 
However, looking at the data we see boolean values mixed with other data types.

Why is this variable given a data type of 'object'?

"""

"\nExecise\n\nUse the head() and info() functions to view information about the _census_ dataframe.\n\nNote that the variable 'above_ground_sighter' is given a dtype of 'object' (str). \nHowever, looking at the data we can see it's boolean.\n\nWhy? Can you explain why this happened, and whether pandas misinterpreted the data type?\n\n"

In [15]:
# the trucated output makes it hard to tell if other variables are affected by the inconsistent capitalization of T/F
# how can we dig deeper - it's important to be thorough!
# there are multiple ways, but one is to use describe()

# by default, outputs desc stats of numeric dtypes
census.describe()

                 x            y          date  hectare_squirrel_number
count  3023.000000  3023.000000  3.023000e+03              3023.000000
mean    -73.967184    40.780853  1.011949e+07                 4.123718
std       0.007726     0.010285  4.246671e+04                 3.096492
min     -73.981159    40.764911  1.006202e+07                 1.000000
25%     -73.973102    40.771676  1.008202e+07                 2.000000
50%     -73.968594    40.778166  1.012202e+07                 3.000000
75%     -73.960189    40.791219  1.014202e+07                 6.000000
max     -73.949722    40.800119  1.020202e+07                23.000000

In [22]:
# In our case this may not be super useful - x and y are geo coordinates, date is its own data type
# Hectare squirrel number is more informative - read data as squirrels per hectare
# suggests that squirrel distribution across hectares is possibly skewed left but we will see!
census['hectare_squirrel_number'].describe()

count    3023.000000
mean        4.123718
std         3.096492
min         1.000000
25%         2.000000
50%         3.000000
75%         6.000000
max        23.000000
Name: hectare_squirrel_number, dtype: float64

In [23]:
# change the default behavior of describe()
# all data types
census.describe(include='all')

,x,y,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,combination_of_primary_and,running,chasing,...,geocoded_column,primary_fur_color,location,above_ground_sighter,age,color_notes,highlight_fur_color,specific_location,other_activities,other_interactions
count,3023.000000,3023.000000,3023,3023,3023,3.023000e+03,3023.000000,3023,3023,3023,...,3023,2968,2959,2909,2902,182,1937,476,437,240
unique,NaN,NaN,3018,339,2,NaN,NaN,22,2,2,...,3023,3,2,41,3,135,10,304,307,197
top,NaN,NaN,7D-PM-1010-01,14D,PM,NaN,NaN,Gray+,False,False,...,"{'type': 'Point', 'coordinates': [-73.95613449...",Gray,Ground Plane,FALSE,Adult,Gray & Cinnamon selected as Primary. White sel...,Cinnamon,tree,digging,runs from (dog)
freq,NaN,NaN,2,32,1676,NaN,NaN,895,2293,2744,...,1,2473,2116,2116,2568,9,767,43,19,9
mean,-73.967184,40.780853,NaN,NaN,NaN,1.011949e+07,4.123718,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.007726,0.010285,NaN,NaN,NaN,4.246671e+04,3.096492,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,-73.981159,40.764911,NaN,NaN,NaN,1.006202e+07,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,-73.973102,40.771676,NaN,NaN,NaN,1.008202e+07,2.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,-73.968594,40.778166,NaN,NaN,NaN,1.012202e+07,3.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,-73.960189,40.791219,NaN,NaN,NaN,1.014202e+07,6.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,-73.949722,40.800119,NaN,NaN,NaN,1.020202e+07,23.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# or by data types
# we have seen numeric types
# 'unique' doesn't count NAs, so we know there are instance of True in each boolean variable
census.describe(include="boolean")

,running,chasing,climbing,eating,foraging,kuks,quaas,moans,tail_flags,tail_twitches,approaches,indifferent,runs_from
count,3023,3023,3023,3023,3023,3023,3023,3023,3023,3023,3023,3023,3023
unique,2,2,2,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,False,False,False
freq,2293,2744,2365,2263,1588,2921,2973,3020,2868,2589,2845,1569,2345

In [25]:
# object or char data type
# this is useful - count of unique is less than the total count
# what does this mean? were some squirrels counted twice? were different squirrels given the same unique_squirrel_id?
# 5 squirrels does not seem statistically significant, but for transparency/QA/QC we should deal with this prior to any analysis
census.describe(include='object')

,unique_squirrel_id,hectare,shift,combination_of_primary_and,geocoded_column,primary_fur_color,location,above_ground_sighter,age,color_notes,highlight_fur_color,specific_location,other_activities,other_interactions
count,3023,3023,3023,3023,3023,2968,2959,2909,2902,182,1937,476,437,240
unique,3018,339,2,22,3023,3,2,41,3,135,10,304,307,197
top,7D-PM-1010-01,14D,PM,Gray+,"{'type': 'Point', 'coordinates': [-73.95613449...",Gray,Ground Plane,FALSE,Adult,Gray & Cinnamon selected as Primary. White sel...,Cinnamon,tree,digging,runs from (dog)
freq,2,32,1676,895,1,2473,2116,2116,2568,9,767,43,19,9

In [32]:
# So - above_ground_sighter has 41 unique values, so it can't be changed to boolean
# what are the other values?
# group the data and see - we will come back to this later
census.groupby('above_ground_sighter')['unique_squirrel_id'].count()

above_ground_sighter
0           1
1          30
10        116
100         5
11          2
12         16
13         11
14          2
15         71
16          2
17          3
18          5
180         1
19          1
2          55
20         84
23          2
24          2
25         33
28          7
3          52
30         44
31          1
33          1
35         10
4          42
40         25
43          2
45          4
5          51
50         19
55          1
6          32
60          3
65          2
7          19
70          1
8          30
80          1
9           4
FALSE    2116
Name: unique_squirrel_id, dtype: int64

In [40]:
"""
above_ground_sighter variable definition:

"Measurement. For squirrel sightings on the ground plane, fields were populated with a value of “FALSE.”"

Do we assume the numeric entries represent feet above the ground plane? If so, how is FALSE different from 0?
More importantly, how do we use these data? If for example we wanted to know if certain species climb higher or are above the ground plane
more frequently?

"""
# we can convert to numeric data, but all FALSE values will be converted to NaN
# if we are interested in using these data, this may be the only option
print(pd.to_numeric(census['above_ground_sighter'], errors='coerce'))

0        NaN
1        NaN
2       10.0
3        NaN
4        NaN
        ...
3018     NaN
3019     NaN
3020     NaN
3021     NaN
3022     NaN
Name: above_ground_sighter, Length: 3023, dtype: float64

In [43]:
# but we don't want to overwrite existing values - it's better to keep the original data intact
# and pandas doesn't like to overwrite cell values in any case
# so we create a new column, but not on inspection that we lost a lot of data in this col
#     - compare with the original above_ground_sighter values
census['above_ground_sighter_n'] = pd.to_numeric(census['above_ground_sighter'], errors='coerce')
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   x                           3023 non-null   float64
 1   y                           3023 non-null   float64
 2   unique_squirrel_id          3023 non-null   object
 3   hectare                     3023 non-null   object
 4   shift                       3023 non-null   object
 5   date                        3023 non-null   int64
 6   hectare_squirrel_number     3023 non-null   int64
 7   combination_of_primary_and  3023 non-null   object
 8   running                     3023 non-null   bool
 9   chasing                     3023 non-null   bool
 10  climbing                    3023 non-null   bool
 11  eating                      3023 non-null   bool
 12  foraging                    3023 non-null   bool
 13  kuks                        3023 non-null   bool
 14  quaas                       3023 non-null   bool
 15  moans                       3023 non-null   bool
 16  tail_flags                  3023 non-null   bool
 17  tail_twitches               3023 non-null   bool
 18  approaches                  3023 non-null   bool
 19  indifferent                 3023 non-null   bool
 20  runs_from                   3023 non-null   bool
 21  geocoded_column             3023 non-null   object
 22  primary_fur_color           2968 non-null   object
 23  location                    2959 non-null   object
 24  above_ground_sighter        2909 non-null   object
 25  age                         2902 non-null   object
 26  color_notes                 182 non-null    object
 27  highlight_fur_color         1937 non-null   object
 28  specific_location           476 non-null    object
 29  other_activities            437 non-null    object
 30  other_interactions          240 non-null    object
 31  above_ground_sighter_int    793 non-null    float64
 32  above_ground_sighter_n      793 non-null    float64
dtypes: bool(13), float64(4), int64(2), object(14)
memory usage: 510.8+ KB

In [48]:
# before further inspection or analysis, 'date' is a dtype in pandas
# we need to convert the date data 
# pandas has excellent datetime handling
census['iso_date'] = pd.to_datetime(census['date'], format='%m%d%Y')
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   x                           3023 non-null   float64
 1   y                           3023 non-null   float64
 2   unique_squirrel_id          3023 non-null   object
 3   hectare                     3023 non-null   object
 4   shift                       3023 non-null   object
 5   date                        3023 non-null   int64
 6   hectare_squirrel_number     3023 non-null   int64
 7   combination_of_primary_and  3023 non-null   object
 8   running                     3023 non-null   bool
 9   chasing                     3023 non-null   bool
 10  climbing                    3023 non-null   bool
 11  eating                      3023 non-null   bool
 12  foraging                    3023 non-null   bool
 13  kuks                        3023 non-null   bool
 14  quaas                       3023 non-null   bool
 15  moans                       3023 non-null   bool
 16  tail_flags                  3023 non-null   bool
 17  tail_twitches               3023 non-null   bool
 18  approaches                  3023 non-null   bool
 19  indifferent                 3023 non-null   bool
 20  runs_from                   3023 non-null   bool
 21  geocoded_column             3023 non-null   object
 22  primary_fur_color           2968 non-null   object
 23  location                    2959 non-null   object
 24  above_ground_sighter        2909 non-null   object
 25  age                         2902 non-null   object
 26  color_notes                 182 non-null    object
 27  highlight_fur_color         1937 non-null   object
 28  specific_location           476 non-null    object
 29  other_activities            437 non-null    object
 30  other_interactions          240 non-null    object
 31  above_ground_sighter_int    793 non-null    float64
 32  above_ground_sighter_n      793 non-null    float64
 33  iso_date                    3023 non-null   datetime64[ns]
dtypes: bool(13), datetime64[ns](1), float64(4), int64(2), object(14)
memory usage: 534.5+ KB

In [50]:
census[['date', 'iso_date']].head()

       date   iso_date
0  10142018 2018-10-14
1  10192018 2018-10-19
2  10142018 2018-10-14
3  10172018 2018-10-17
4  10172018 2018-10-17

In [ ]:
# now we have cleaned up our data a little
# let's look at selecting and slicing data